store_features:
  - diner_review_cnt_category
  - min_price
  - max_price
  - mean_price
  - median_price
  - menu_count
  - taste
  - kind
  - mood
  - chip
  - parking
  - asian
  - japanese
  - chinese
  - korean
  - western

cat_features:
  - diner_review_cnt_category
