name: catboost

model_path: result/catboost/
results: catboost_rank

params:
  task_type: GPU
  loss_function: YetiRank
  eval_metric: NDCG
  learning_rate: 0.05
  l2_leaf_reg: 0.02
  bagging_temperature: 3
  min_data_in_leaf: 57
  od_type: Iter
  iterations: 20000
  allow_writing_files: False

early_stopping_rounds: 100
seed: 42
verbose_eval: 100