_target_: src.model.rank.boosting.LightGBMTrainer

model_path: result/lightgbm/
results: lgb_ranker

features:
  - diner_review_cnt_category
  - min_price
  - max_price
  - mean_price
  - median_price
  - menu_count
  - taste
  - kind
  - mood
  - chip
  - parking
  - asian
  - japanese
  - chinese
  - korean
  - western

cat_features:
  - diner_review_cnt_category

params:
  objective: lambdarank
  boosting_type: gbdt
  metric: ndcg
  ndcg_at:
    - 3
    - 7
    - 10
    - 20
  bagging_freq: 5
  bagging_fraction: 0.8
  feature_fraction: 0.8
  learning_rate: 0.05
  max_depth: -1
  num_leaves: 16
  verbose: -1
  n_jobs: -1

early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42
