name: lightgbm

model_path: result/lightgbm/
results: lgb_ranker

params:
  objective: lambdarank
  boosting_type: gbdt
  metric: ndcg
  ndcg_at:
    - 3
    - 7
    - 10
    - 20
  bagging_freq: 5
  bagging_fraction: 0.8
  feature_fraction: 0.8
  learning_rate: 0.05
  max_depth: -1
  num_leaves: 64
  min_data_in_leaf: 100
  min_sum_hessian_in_leaf: 10
  max_bin: 255
  min_child_samples: 20
  min_child_weight: 0.001
  scale_pos_weight: 1
  lambda_l1: 0.01
  lambda_l2: 0.01
  verbose: -1
  n_jobs: -1

early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42