name: lightgbm

model_path: res/models/
results: lightgbm_ranker

params:
  objective: lambdarank
  boosting_type: gbdt
  metric: ndcg
  ndcg_at:
    - 3
    - 5
    - 10
    - 20
  bagging_freq: 5
  bagging_fraction: 0.8
  feature_fraction: 0.8
  learning_rate: 0.1
  max_depth: -1
  num_leaves: 16
  verbose: -1
  n_jobs: -1

early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42