name: lightgbm

model_path: res/models/
results: lightgbm_ranker

params:
  objective: rank_xendcg
  metric: ndcg
  boosting_type: gbdt
  learning_rate: 0.01
  max_depth: -1
  num_leaves: 16
  verbose: -1
  n_jobs: -1

early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42