name: xgboost

model_path: res/models/
results: xgb_ranker

params:
  objective: rank:ndcg
  method: hist
  eval_metric:
    - ndcg@10
    - ndcg@15
    - ndcg@20
  eta: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  alpha: 0.01
  lambda: 0.01
  n_jobs: -1

early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
seed: 42