filter:
  martial_law_reviews:
    target_months:
      - 2025-01
      - 2024-12
    min_common_word_count_with_abusive_words: 3
    min_review_count_by_diner_id: 3
    included_tags:
      - NNG
      - NNP
    abusive_words:
      - 총
      - 내란
      - 공수처
      - 시위
      - 좌우
      - 애국
      - 정치
      - 총살
      - 테러
      - 민주주의
      - 윤석열
      - 총기
      - 좌파
      - 우파
      - 극우
      - 집회
      - 계엄
    # this diner_ids are pre-calculated from above filter config to avoid redundant calculation
    pre_calculated_diner_ids:
      - 20557155
      - 561814157
      - 717255023
      - 1210281986
      - 1210386151
      - 1275807781
      - 1390211388
      - 1420824177
      - 1567102742
      - 1983344097
