hydra:
  run:
    dir: .
  output_subdir: null
  
defaults:
  - _self_
  - data: dataset
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

model_path: res/models/
results: lightgbm_ranker
user_name: 893438059
diner_middle_category: 한식
diner_address_constituency: 서울 노원구
top_n: 10
size: 1000