hydra:
  job_logging:
      root:
        handlers: [console]
        level: INFO  # 로그 레벨
      handlers:
        console:
          class: logging.StreamHandler
          level: INFO
          formatter: simple
      formatters:
        simple:
          format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  run:
    dir: .
  output_subdir: null

defaults:
  - _self_
  - data: dataset
  - models/ranker: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

model_path: res/models/
results: lightgbm_ranker
user_name: 3830746302
top_n: 20
user_address: 목동역
distance_threshold: 1
diner_category_large:
- 양식
- 중식
- 치킨
- 한식
- 일식
- 아시아음식
