hydra:
  job_logging:
      root:
        handlers: [console]
        level: INFO  # 로그 레벨
      handlers:
        console:
          class: logging.StreamHandler
          level: INFO
          formatter: simple
      formatters:
        simple:
          format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  run:
    dir: .
  output_subdir: null
  
defaults:
  - _self_
  - data: dataset
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

diner_engineered_feature_names:
  - all_review_cnt

model_path: res/models/
results: lightgbm_ranker
user_name: 3830746302
top_n: 20
user_lat: 37.498095
user_lon: 127.027610
distance_threshold: 1
diner_category_middle:
- 육류,고기
- 해물,생선
- 치킨
- 중식
