hydra:
  job_logging:
      root:
        handlers: [console]
        level: INFO  # 로그 레벨
      handlers:
        console:
          class: logging.StreamHandler
          level: INFO
          formatter: simple
      formatters:
        simple:
          format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  run:
    dir: .
  output_subdir: null

defaults:
  - _self_
  - data: dataset
  - features: store
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

training:
  evaluation:
    recommend_batch_size: 1000
    top_k_values_for_pred:
      - 3
      - 7
      - 10
      - 20
    top_k_values_for_candidate:
      - 100
      - 300
      - 500
      - 1000
      - 2000
