preprocess:
  data:
    min_review: 3
  feature_engineering:
    diner_engineered_feature_names:
      diner_category_meta_combined_with_h3:
        category_column_for_meta: diner_category_middle
        h3_resolution: 9
    user_engineered_feature_names: {}
training:
  near_candidate:
    max_distance_km: 1
  torch:
    device: cpu
  evaluation:
    recommend_batch_size: 1000
    top_k_values_for_pred:
      - 3
      - 7
      - 10
      - 20
    top_k_values_for_candidate:
      - 100
      - 300
      - 500
      - 1000
      - 2000
post_training:
  file_name:
    log: log.log
    weight: weight.pt
    training_loss: training_loss.pkl
    metric: metric.pkl
    data_object: data_object.pkl
    user_mapping: user_mapping.pkl
    diner_mapping: diner_mapping.pkl
    candidate: candidate.parquet
  candidate_generation:
    top_k: 100
